### ISSUE TITLE
Package does not install in VS 2019

### ISSUE THREAD

**Issue by elhaix** [pvdstel/scrcpy-vs#3]
Hi there,

I am trying to get scrcpy to run in Visual Studio by using this extension and determine if I can extend its features using C#.  Will this provide that functionality?

I haven't gotten this working yet... still trying as it does not install.

**Does this simply open the app in VS or do can I now extend the scrcpy functionalities through .Net?**

**Can you please provide some more documentation on features, etc????**

Error when installing:  This extension is not installable on any currently installed products

I updated the <InstallationTarget> and <Dependency> in the manifest file:

Unable to install a VSIX extension for Visual Studio 2019

Installation fails indicating:

enter image description here

I updated the <InstallationTarget> and <Dependency> as per here,

You need to change InstallationTarget to [15.0,17.0) and Prerequisite to [15.8.27729.1,).

I unzipped the .vsix file, updated the extension.vsixmanifest file to the following:
```

<Installation>
    <InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[15.0,17.0)" />
  </Installation>
  <Dependencies>
    <Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" Version="[4.5,)" />
    <Dependency Id="Microsoft.VisualStudio.MPF.15.0" DisplayName="Visual Studio MPF 15.0" Version="[15.0]" />
  </Dependencies>
  <Prerequisites>
    <Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[15.8.27729.1,)" DisplayName="Visual Studio core editor" />
  </Prerequisites>
```

Zipped the directory, renamed to *.vsix, tried to install again.

The installer now recognizes Visual Studio 2019, begins installing but fails, missing Microsoft.VisualStudio.Component.CoreEditor.

```
12/11/2019 5:25:00 PM - Beginning to install extension to Visual Studio Enterprise 2019 (2)...
12/11/2019 5:25:02 PM - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
-Microsoft.VisualStudio.Component.CoreEditor (Microsoft.VisualStudio.Component.CoreEditor)
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.EnsureNoMissingReferences(IEnumerable`1 missingRefs)
   at Microsoft.VisualStudio.ExtensionManager.PackageInstaller.PrepareEngineInstall(IDependencyGraph dGraph, IDependencyComparisonSeed seed, Component vsixComponent, Boolean isProductComponent, Int32& totalInstallationSteps)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
```

https://stackoverflow.com/questions/59295089/missing-microsoft-visualstudio-component-coreeditor-when-installing-visual-studi

**Comment by elhaix** [comment]
For anyone having an issue with this, unzip the .vsix file, do the following then zip the contents of the directory back up and run the .vsix.

In extension.vsixmanifest, change InstallationTarget to [15.0,17.0) and Prerequisite to [15.8.27729.1,).

```
<Installation InstalledByMsi="false"> 
    <InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="[14.0,17.0)" /> 
</Installation>

<Prerequisites> 
    <Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[15.0,)" DisplayName="Visual Studio core editor" /> 
</Prerequisites>


```
--

Apart from the changes to extension.vsixmanifest file, also change "Microsoft.VisualStudio.Component.CoreEditor":"[15.0,16.0)" in catalog.json file
```

    "packages": [{
            "id": "Component.scrcpy-vs.dc2f8ff9-ed86-419d-8b82-5400c90cef8f",
            "version": "0.4",
            "type": "Component",
            "extension": true,
            "dependencies": {
                "scrcpy-vs.dc2f8ff9-ed86-419d-8b82-5400c90cef8f": "0.4",
                "Microsoft.VisualStudio.Component.CoreEditor": "[15,)"
            },

```

**Comment by pvdstel** [comment]
Hi @elhaix, I've pushed an update to the marketplace that adds support for Visual Studio 2019.
